apiVersion: apps/v1
kind: Deployment # 部署镜像
metadata:
  name: routetestdev # 部署命名
  namespace: ai-itest # 命名空间
spec:
  selector:
    matchLabels:
      name: routetest
      version: v2
  minReadySeconds: 60
  replicas: 1 # 集群数量
  strategy: 
    rollingUpdate: # 滚动升级策略
      maxSurge: 1
      maxUnavailable: 0
  template: # 部署服务模板
    metadata:
      labels:
        name: routetest
        version: v2 # 服务标签，被Service代理集群时选择
    spec:
      containers:
      - name: routetestdev # 服务名
        image: registry.cn-hangzhou.aliyuncs.com/jiangruicheng/routetest:v1 # 镜像下载地址
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 4096Mi
          requests:
            cpu: 500m
            memory: 2048Mi
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
        env:
        - name: JAVA_OPTS # Java启动参数
          value: "-Dspring.profiles.active=dev -Xms1024M -Xmx1024M"

---
apiVersion: v1
kind: Service # 容器的统一服务入口
metadata:
  name: routetestdev # 服务名
  namespace: ai-itest # 命名空间
spec:
  type: ClusterIP
  ports:
  - port: 8080 # 服务端口，用于集群内部访问
    targetPort: 8080 # 容器端口
  selector:
    name: routetest
    version: v2 # 选择指定标签的服务，统一暴漏端口

